name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com

    steps:
      - uses: actions/checkout@v2

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Build project
        run: msbuild RandomStringGenerator.sln
        
      - name: Build with devenv.com
        shell: cmd
        run: |
          "%MSBUILD_PATH%" RandomStringGenerator.sln /build debug
